title: Elliott Evans
logo: /assets/img/logo.png
location: Chicago, IL
email: evanselliott1@gmail.com
linkedin: elliott-evans
github: elliottevans
description: Minimal is a theme for GitHub Pages.
show_downloads: true
theme: jekyll-theme-minimal
