title: Elliott Evans
logo: /assets/img/profile_pic.jpeg
location: Chicago, IL
email: evanselliott1@gmail.com
linkedin: elliott-evans
github: elliottevans
show_downloads: false
theme: jekyll-theme-minimal
